version: '3.8'

# 从根目录 .env 文件加载环境变量

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ${COMPOSE_PROJECT_NAME:-ai-stock}-backend
    volumes:
      - ${DATA_VOLUME:-./data}:/app/data
      - ${LOGS_VOLUME:-./logs}:/app/logs
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_HOURS=${ACCESS_TOKEN_EXPIRE_HOURS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: ${COMPOSE_PROJECT_NAME:-ai-stock}-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME:-ai-stock}-nginx
    ports:
      - "${NGINX_PORT:-8080}:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data: