version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: landing-nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: landing-backend
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/db.sqlite
      - SECRET_KEY=your-production-secret-key-change-this
      - ALLOWED_ORIGINS=["*"]
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: landing-frontend
    expose:
      - "80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data: